### ISSUE TITLE
Pre-flight error

### ISSUE THREAD

**Issue by c33k** [GoThinkster/productionready#1]
Hello, guys.

I'm making the [Build an Angular 1.5 application with ES6 and Components](https://thinkster.io/angularjs-es6-tutorial#using-components-directives-for-reusable-ui-functionality) tutorial and, when I try to make a POST request using _$http_ for _/api/users_, like specified in **API.md**, I get an error on the pre-flight:

`XMLHttpRequest cannot load https://conduit.productionready.io/api/users. Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:4000, *', but only one is allowed. Origin 'http://localhost:4000' is therefore not allowed access.`

I made the same request using **curl** on my console and got no error. I was able to create a new user and also login (i.e. no OPTION request, no pre-flight).

`$ curl -X POST https://conduit.productionready.io/api/users -vsL -d "{\"user\":{\"email\":\"rltoscano@gmail.com\", \"password\":\"12345678\"}}" -H 'Content-type: application/json'`

So, it seems to be a server side problem. Can someone check it, please?

**Comment by c33k** [comment]
You could check if there's any code that enable CORS twice.

**Comment by apai4** [comment]
CORS is enabled (once) to allow any origin

`$ curl -X OPTIONS -D - -H 'Origin: http://localhost:4000' -H "Access-Control-Request-Method: POST" https://conduit.productionready.io/api/users`

includes

`Access-Control-Allow-Origin: http://localhost:4000`

as a response header (no extra wildcard). Changing the URL in the `Origin` request header will yield an `Access-Control-Allow-Origin: ` response header with only that URL as the value.

What browser are you using? Could it be a browser extension that's interfering with that header?

**Comment by c33k** [comment]
@apai4: you're right. It was a browser extension!

Someone installed the **CORS Toggle** in this machine's Google Chrome that I'm using and it was enabled, causing this problem.  

Thank you!
